version: "3.8" # Updated to a more common recent version

services:
  postgresdb:
    image: postgres:13 # Using postgres:13 like in our previous setup
    hostname: metastore_db
    container_name: tutorial_postgres 
    restart: always
    environment:
      POSTGRES_USER: hive 
      POSTGRES_PASSWORD: hive 
      POSTGRES_DB: metastore 
    volumes:
      - postgres_data_tutorial:/var/lib/postgresql/data # Use a named volume
    networks:
      - trino_network_tutorial # Use a custom network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://trino-data/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - trino_network_tutorial

  trino-coordinator:
    image: 'trinodb/trino:400' # As per tutorial
    hostname: trino-coordinator
    container_name: tutorial_trino_coordinator # Added for clarity
    restart: always
    ports:
      - '8080:8080'
    volumes:
      # IMPORTANT: The tutorial expects host paths like /data/trino/etc
      # We will adapt this to use relative paths for better portability,
      # assuming you have a 'trino-files-tutorial' directory next to your docker-compose.yml
      # where config.properties, node.properties, jvm.config, and catalog/ (for hive.properties, delta.properties) reside.
      - ./trino-files-tutorial/etc:/etc/trino
    depends_on: # Trino depends on Hive Metastore
      hive-metastore
      minio: # Trino also depends on MinIO
        condition: service_healthy
    networks:
      - trino_network_tutorial
    # Add extra_hosts for host.docker.internal if any config still uses it,
    # but best to use service names like 'minio' and 'hive-metastore'.
    # For this tutorial, direct service name resolution is better.

  minio: # Added MinIO service
    image: minio/minio:latest
    hostname: minio
    container_name: tutorial_minio # Added for clarity
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio_data_tutorial:/data # Use a named volume
    environment:
      MINIO_ROOT_USER: minioadmin # Consistent credentials
      MINIO_ROOT_PASSWORD: minioadmin # Consistent credentials
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - trino_network_tutorial

volumes:
  postgres_data_tutorial: # Renamed volume
  minio_data_tutorial:    # Added volume for MinIO

networks:
  trino_network_tutorial: # Renamed network
    driver: bridge